# Generated by Django 4.2.10 on 2024-03-08 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SkyBubbles', '0002_product_created_date_product_deleted_product_length_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size_h', models.FloatField()),
                ('size_w', models.FloatField()),
                ('weight', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.category')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='current_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_price', to='SkyBubbles.price', verbose_name='Текущая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удален?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ширина'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('active', models.BooleanField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.ingredient')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.partner')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.storage')),
            ],
        ),
    ]
