# Generated by Django 4.2.10 on 2024-03-09 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SkyBubbles', '0004_alter_category_options_alter_ingredient_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='active',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='count',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='storage',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Acceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('active', models.BooleanField()),
                ('createFd_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.ingredient')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.partner')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.storage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Приход',
                'verbose_name_plural': 'Приходы',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='acceptance',
            field=models.ManyToManyField(to='SkyBubbles.acceptance'),
        ),
    ]
