# Generated by Django 4.2.10 on 2024-03-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SkyBubbles', '0005_alter_transaction_options_remove_transaction_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='createFd_date',
            new_name='created_date',
        ),
    ]
