# Generated by Django 4.2.10 on 2024-03-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SkyBubbles', '0006_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
