# Generated by Django 4.2.10 on 2024-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyBubbles', '0007_alter_category_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='price',
            new_name='price_delivery',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='acceptance',
        ),
        migrations.AddField(
            model_name='transaction',
            name='acceptance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.acceptance'),
            preserve_default=False,
        ),
    ]
