# Generated by Django 4.2.10 on 2024-03-09 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyBubbles', '0008_rename_price_transaction_price_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='acceptance',
        ),
        migrations.AddField(
            model_name='acceptance',
            name='Transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.transaction'),
            preserve_default=False,
        ),
    ]
