# Generated by Django 4.2.10 on 2024-03-09 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SkyBubbles', '0009_remove_transaction_acceptance_acceptance_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.RenameField(
            model_name='acceptance',
            old_name='createFd_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='createFd_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='createFd_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='createFd_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='createFd_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='createFd_date',
            new_name='created_date',
        ),
        migrations.AlterField(
            model_name='acceptance',
            name='Transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SkyBubbles.transaction', verbose_name='Поставка'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price_delivery',
            field=models.IntegerField(verbose_name='Стоимость доставки'),
        ),
    ]
